### ISSUE TITLE
Explicit namespace in Role (and RoleBinding)

### ISSUE THREAD

**Issue by espositocloud** [figwasp/figwasp#2]
In the README, a Role (and RoleBinding) is used in order to provide permissions to the CronJob.

Since a Role is scoped at namespace level, I would make `namespace` explicit in the Role and RoleBinding definitions.

Also, as alternative a ClusterRole (and a ClusterRoleBinding) can be used instead.

**Comment by joel-ling** [comment]
Thank you, @espositocloud, for pointing out the error.

Indeed, Roles and RoleBindings are not valid unless a namespace is specified.

https://kubernetes.io/docs/reference/access-authn-authz/rbac/#role-and-clusterrole
> A Role always sets permissions within a particular namespace; when you create a Role, you have to specify the namespace it belongs in.

To rectify the errors, I have edited the Role and RoleBinding manifests in the [`README`](https://github.com/figwasp/figwasp#configure-permissions).

I also considered the option of using ClusterRole(Binding)s, but am concerned that such an example might infringe on the [principle of least privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege).

Nonetheless, your suggestion has inspired the idea of supplying an option for Figwasp to manage Deployments across all namespaces in a cluster. Such a feature would justify the use of ClusterRoles and ClusterRoleBindings.

Thank you for your contribution to the project!
