### ISSUE TITLE
Support multiple Deployments dinamically

### ISSUE THREAD

**Issue by espositocloud** [figwasp/figwasp#4]
Currently a single resource can be monitored and it's configured via the `FIGWASP_TARGET_DEPLOYMENT` environment variable in the Figwasp manifest.

Using annotations (such as `figwasp/target: true` or similar) attached to the monitored Deployments brings some benefits:

- more Deployments can be monitored, without the need of setting a list in the same environment variable
- Deployments can be added and removed naturally by adding/editing/removing the annotation
- prevents to update Figwasp itself

**Comment by joel-ling** [comment]
Thank you, @espositocloud, for your suggestion!

The benefits of using a label to simultaneously and dynamically target multiple Deployments are significant.

I have released a [new version](https://github.com/figwasp/figwasp/releases/tag/v2.0.0) of Figwasp incorporating the changes you proposed.

Thank you for your contribution to the project!
